{% set name = "recordlinkage" %}
{% set version = "0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

  sha256: ecda0c10dff138b1706815de332b1285f670ae7e8cce92596213501d589e6aa4


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.13
    - pandas >=1,<3
    - scipy >=1
    - scikit-learn >=1
    - jellyfish>=1
    - joblib
    - numexpr

test:
  imports:
    - recordlinkage

about:
  home: https://github.com/J535D165/recordlinkage
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python library to link records in or between data sources
  doc_url: https://recordlinkage.readthedocs.io/


extra:
  recipe-maintainers:
    - Maerville
