{% set name = "recordlinkage" %}
{% set version = "0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

  sha256: 688af1e78be77fce48fca8adff89e383f5483aee87d1213b35d43519b78ff027


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - pandas >=0.18.0
    - scipy
    - scikit-learn
    - jellyfish
    - numexpr

test:
  imports:
    - recordlinkage

about:
  home: https://github.com/J535D165/recordlinkage
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python library to link records in or between data sources
  doc_url: https://recordlinkage.readthedocs.io/


extra:
  recipe-maintainers:
    - Maerville
